from qlearningplayer import QLearningPlayer
from humanplayer import HumanPlayer
from fastqlearningplayer import FastQLearningPlayer
from minimaxplayer import MinimaxPlayer
from baseplayer import available_players
